### ISSUE TITLE
Share your theme with the community

### ISSUE THREAD

**Issue by digitalcraftsman** [juh2/hugo-phantom#1]
Hello @juh2,

all Hugo themes are usually listed in the [hugoThemes](https://github.com/spf13/hugoThemes/) repository. The list is used to  generate the website [themes.gohugo.io](http://themes.gohugo.io/) that allows users to browse all themes and watch a demo of them.

If you like to add your theme to the list follow the steps listed [here](https://github.com/spf13/hugoThemes/#adding-a-theme-to-the-list) and open an issue to let us know.

Cheers,
Digitalcraftsman

**Comment by juh2** [comment]
I'll do this. Thanks.

**Comment by UnsolvedCypher** [comment]
Any update on that?

**Comment by juh2** [comment]
No, my theme isn't listed there. I forgot to do this. And there is also a project to automatically convert html5 themes to hugo. So I thought that it is not needed. See here: https://github.com/bep/html5up-to-hugo
